version: "3.2"
services:
  web:
    image: centos7_last
    hostname: Anonymous
    build: .
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
    volumes:
      - type: bind
        source: dockerlampplast
        target: /opt/lampp
      - type: bind
        source: ~/Documents/
        target: /opt/lampp/htdocs/share/
  redis:
    image: "redis:alpine"
volumes:
  dockerlampplast:
