version: "3.2"
services:
  web:
    image: centos7_last
    hostname: Anonymous
    build: .
    ports:
      - "8000:80"
      - "3306:3306"
      - "22:22"
    volumes:
      - type: bind
        source: dockerlampplast
        target: /opt/lampp
      - type: bind
        source: ~/Documents/cht/esteban
        target: /opt/lampp/htdocs/
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
volumes:
  dockerlampplast:
