version: "3.2"
services:
  web:
    image: centos7_web
    hostname: Anonymous
    build: .
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
    volumes:
      - type: bind
        source: dockerlampp
        target: /opt/lampp
      - type: bind
        source: ~/Documents/cht/henry
        target: /opt/lampp/htdocs/share
  redis:
    image: "redis:alpine"
volumes:
  dockerlampp:
